default:
  image: oven:bun:alpine

stages:
  - build

build:
  stage: build
  script:
    - echo "building..."
    - bun ci
    - bun run build
    - echo "deploying..."

  artifacts:
    paths:
      - public
  when: manual
